"""Criação de contrato_id em Proposta e exclusao de proposta_id em Contrato

Revision ID: 27d63b9d5889
Revises: 5f34cbfeb865
Create Date: 2025-06-03 18:04:23.969171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d63b9d5889'
down_revision = '5f34cbfeb865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_constraint('contrato_proposta_id_fkey', type_='foreignkey')
        batch_op.drop_column('proposta_id')

    with op.batch_alter_table('proposta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrato_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'contrato', ['contrato_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('contrato_id')

    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposta_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('contrato_proposta_id_fkey', 'proposta', ['proposta_id'], ['id'])

    # ### end Alembic commands ###
