"""Apagadas as colunas de nf_id de Contrato

Revision ID: 5ddcabd5f924
Revises: b755266f5090
Create Date: 2025-06-09 19:00:34.238640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddcabd5f924'
down_revision = 'b755266f5090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_constraint('contrato_nf_id_protocolo_fkey', type_='foreignkey')
        batch_op.drop_constraint('contrato_nf_id_aprovacao_fkey', type_='foreignkey')
        batch_op.drop_constraint('contrato_nf_id_assinatura_fkey', type_='foreignkey')
        batch_op.drop_column('nf_id_assinatura')
        batch_op.drop_column('nf_id_protocolo')
        batch_op.drop_column('nf_id_aprovacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nf_id_aprovacao', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nf_id_protocolo', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nf_id_assinatura', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('contrato_nf_id_assinatura_fkey', 'nota_fiscal', ['nf_id_assinatura'], ['id'])
        batch_op.create_foreign_key('contrato_nf_id_aprovacao_fkey', 'nota_fiscal', ['nf_id_aprovacao'], ['id'])
        batch_op.create_foreign_key('contrato_nf_id_protocolo_fkey', 'nota_fiscal', ['nf_id_protocolo'], ['id'])

    # ### end Alembic commands ###
