"""Criação da coluna Proposta na tabela Contrato

Revision ID: 5f34cbfeb865
Revises: bd101cb3bf83
Create Date: 2025-06-02 20:15:32.680452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f34cbfeb865'
down_revision = 'bd101cb3bf83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposta_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'proposta', ['proposta_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proposta_id')

    # ### end Alembic commands ###
