"""Criação de nf_id para ass prot e conclus em Contrato

Revision ID: b755266f5090
Revises: 27d63b9d5889
Create Date: 2025-06-09 18:29:10.906481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b755266f5090'
down_revision = '27d63b9d5889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nf_id_assinatura', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nf_id_protocolo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nf_id_aprovacao', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'nota_fiscal', ['nf_id_aprovacao'], ['id'])
        batch_op.create_foreign_key(None, 'nota_fiscal', ['nf_id_assinatura'], ['id'])
        batch_op.create_foreign_key(None, 'nota_fiscal', ['nf_id_protocolo'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('nf_id_aprovacao')
        batch_op.drop_column('nf_id_protocolo')
        batch_op.drop_column('nf_id_assinatura')

    # ### end Alembic commands ###
