"""Migração inicial

Revision ID: bd101cb3bf83
Revises: 
Create Date: 2025-06-02 12:14:53.239088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd101cb3bf83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('numero_conta', sa.String(length=20), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('observacao', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('observacao', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('escopo', sa.String(length=300), nullable=False),
    sa.Column('data_assinatura', sa.Date(), nullable=False),
    sa.Column('valor_assinatura', sa.Float(), nullable=False),
    sa.Column('status_assinatura', sa.Boolean(), nullable=True),
    sa.Column('data_faturamento_assinatura', sa.Date(), nullable=False),
    sa.Column('valor_protocolo', sa.Float(), nullable=False),
    sa.Column('status_protocolo', sa.Boolean(), nullable=True),
    sa.Column('data_faturamento_protocolo', sa.Date(), nullable=False),
    sa.Column('valor_aprovacao', sa.Float(), nullable=False),
    sa.Column('status_aprovacao', sa.Boolean(), nullable=True),
    sa.Column('data_faturamento_aprovacao', sa.Date(), nullable=False),
    sa.Column('status_contrato', sa.String(length=25), nullable=False),
    sa.Column('numero_contrato', sa.String(length=10), nullable=False),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('numero_proposta', sa.String(length=10), nullable=False),
    sa.Column('data_envio', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('escopo', sa.String(length=300), nullable=False),
    sa.Column('valor_assinatura', sa.Float(), nullable=False),
    sa.Column('valor_protocolo', sa.Float(), nullable=False),
    sa.Column('valor_aprovacao', sa.Float(), nullable=False),
    sa.Column('status_proposta', sa.String(length=25), nullable=False),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota_fiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('numero_nf', sa.Integer(), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('valor_bruto', sa.Float(), nullable=False),
    sa.Column('valor_liquido', sa.Float(), nullable=False),
    sa.Column('forma_de_pagamento', sa.String(length=10), nullable=False),
    sa.Column('boleto', sa.String(length=15), nullable=True),
    sa.Column('banco_id', sa.Integer(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status_pagamento', sa.String(length=15), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servico', sa.String(length=12), nullable=False),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['banco_id'], ['banco.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nota_fiscal')
    op.drop_table('proposta')
    op.drop_table('contrato')
    op.drop_table('cliente')
    op.drop_table('banco')
    # ### end Alembic commands ###
