"""Criar tabela saldo_caixa_mensal

Revision ID: 18859be1f299
Revises: 1d58fa1f59c9
Create Date: 2025-10-14 03:01:14.866574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18859be1f299'
down_revision = '1d58fa1f59c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saldo_caixa_mensal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.Date(), nullable=False))
        batch_op.alter_column('saldo_final',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.drop_constraint('uix_ano_mes', type_='unique')
        batch_op.drop_column('data_registro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saldo_caixa_mensal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_registro', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('uix_ano_mes', ['ano', 'mes'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('saldo_final',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###
