"""Em Contrato e Proposta - alterada as relacoes das tabelas

Revision ID: 1d58fa1f59c9
Revises: 50af59bc41e4
Create Date: 2025-09-30 11:29:46.788077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d58fa1f59c9'
down_revision = '50af59bc41e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposta_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'proposta', ['proposta_id'], ['id'])

    with op.batch_alter_table('proposta', schema=None) as batch_op:
        batch_op.drop_constraint('proposta_contrato_id_fkey', type_='foreignkey')
        batch_op.drop_column('contrato_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrato_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('proposta_contrato_id_fkey', 'contrato', ['contrato_id'], ['id'])

    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proposta_id')

    # ### end Alembic commands ###
