"""Criação do campo Historico na Tabela Propostas

Revision ID: 44c17d718e0e
Revises: a8cd36e511a5
Create Date: 2025-09-27 13:19:28.918625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44c17d718e0e'
down_revision = 'a8cd36e511a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historico', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('versao',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('valor_assinatura',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('valor_protocolo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('valor_conclusao',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposta', schema=None) as batch_op:
        batch_op.alter_column('valor_conclusao',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('valor_protocolo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('valor_assinatura',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('versao',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('historico')

    # ### end Alembic commands ###
