"""Em Contrato - alterado aprovacao para conclusao

Revision ID: 50af59bc41e4
Revises: 44c17d718e0e
Create Date: 2025-09-30 10:30:34.751262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50af59bc41e4'
down_revision = '44c17d718e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_conclusao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status_conclusao', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_faturamento_conclusao', sa.Date(), nullable=True))
        batch_op.drop_column('data_faturamento_aprovacao')
        batch_op.drop_column('status_aprovacao')
        batch_op.drop_column('valor_aprovacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_aprovacao', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status_aprovacao', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_faturamento_aprovacao', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('data_faturamento_conclusao')
        batch_op.drop_column('status_conclusao')
        batch_op.drop_column('valor_conclusao')

    # ### end Alembic commands ###
