"""Migração inicial.

Revision ID: a8cd36e511a5
Revises: 
Create Date: 2025-09-26 11:57:54.267198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8cd36e511a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('observacao',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.drop_column('data_cadastro')

    with op.batch_alter_table('proposta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('versao', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contratos_multiplos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('valor_conclusao', sa.Float(), nullable=True))
        batch_op.alter_column('valor_assinatura',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('valor_protocolo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('valor_aprovacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_aprovacao', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.alter_column('valor_protocolo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('valor_assinatura',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('valor_conclusao')
        batch_op.drop_column('contratos_multiplos')
        batch_op.drop_column('versao')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.alter_column('observacao',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    # ### end Alembic commands ###
